export const RS_REALTIME_PAIR_FILTERS: Record<string, string[]> = {
  realtimePairFilterList: [
  'QQQ-MSFT',
  'QQQ-AMZN',
  'QQQ-GOOGL',
  'QQQ-META',
  'QQQ-NVDA',
  'QQQ-AVGO',
  'QQQ-COST',
  'QQQ-ISRG',
  'QQQ-ADBE',
  'QQQ-NFLX',
  'SPY-AAPL',
  'SPY-MSFT',
  'SPY-AMZN',
  'SPY-GOOGL',
  'SPY-META',
  'SPY-JPM',
  'SPY-JNJ',
  'SPY-HD',
  'SPY-PG',
  'SPY-XOM',
],
};
