import { PositionDoc, PositionDirection, PositionStatus } from '../../core/models/fe-position.types';

export const MOCK_OPEN_POSITIONS: readonly PositionDoc[] = [
  {
    positionId: 'MOCK-SPY-QQQ-LONG-1',
    pair: 'SPY/QQQ',
    baseline: 'SPY',
    symbol: 'QQQ',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 100,
    entryDay: '2025-01-15',
    entryTimestamp: Date.UTC(2025, 0, 15),
    currentPrice: 108,
    currentChange: 8,
    currentPctChange: 8,
    lastUpdateDay: '2025-01-20',
    currentRs: 1.25,
    netPnL: 800,
  },
  {
    positionId: 'MOCK-SPY-AAPL-LONG-2',
    pair: 'SPY/AAPL',
    baseline: 'SPY',
    symbol: 'AAPL',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 95,
    entryDay: '2025-01-10',
    entryTimestamp: Date.UTC(2025, 0, 10),
    currentPrice: 90,
    currentChange: -5,
    currentPctChange: -5.26,
    lastUpdateDay: '2025-01-20',
    currentRs: -0.8,
    netPnL: -500,
  },
  {
    positionId: 'MOCK-IWM-QQQ-LONG-3',
    pair: 'IWM/QQQ',
    baseline: 'IWM',
    symbol: 'QQQ',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 50,
    entryDay: '2025-01-05',
    entryTimestamp: Date.UTC(2025, 0, 5),
    currentPrice: 55,
    currentChange: 5,
    currentPctChange: 10,
    lastUpdateDay: '2025-01-20',
    currentRs: 0.9,
    netPnL: 500,
  },
  {
    positionId: 'MOCK-SPY-TSLA-LONG-4',
    pair: 'SPY/TSLA',
    baseline: 'SPY',
    symbol: 'TSLA',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 120,
    entryDay: '2025-01-03',
    entryTimestamp: Date.UTC(2025, 0, 3),
    currentPrice: 132,
    currentChange: 12,
    currentPctChange: 10,
    lastUpdateDay: '2025-01-20',
    currentRs: 1.6,
    netPnL: 1200,
  },
  {
    positionId: 'MOCK-SPY-MSFT-LONG-5',
    pair: 'SPY/MSFT',
    baseline: 'SPY',
    symbol: 'MSFT',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 110,
    entryDay: '2025-01-08',
    entryTimestamp: Date.UTC(2025, 0, 8),
    currentPrice: 112,
    currentChange: 2,
    currentPctChange: 1.82,
    lastUpdateDay: '2025-01-20',
    currentRs: 0.3,
    netPnL: 200,
  },
  {
    positionId: 'MOCK-QQQ-SPY-SHORT-1',
    pair: 'QQQ/SPY',
    baseline: 'QQQ',
    symbol: 'SPY',
    status: PositionStatus.OPEN,
    direction: PositionDirection.SHORT,
    entryPrice: 300,
    entryDay: '2025-01-04',
    entryTimestamp: Date.UTC(2025, 0, 4),
    currentPrice: 285,
    currentChange: -15,
    currentPctChange: -5,
    lastUpdateDay: '2025-01-20',
    currentRs: 1.1,
    netPnL: 1500,
  },
  {
    positionId: 'MOCK-QQQ-IWM-SHORT-2',
    pair: 'QQQ/IWM',
    baseline: 'QQQ',
    symbol: 'IWM',
    status: PositionStatus.OPEN,
    direction: PositionDirection.SHORT,
    entryPrice: 210,
    entryDay: '2025-01-06',
    entryTimestamp: Date.UTC(2025, 0, 6),
    currentPrice: 220,
    currentChange: 10,
    currentPctChange: 4.76,
    lastUpdateDay: '2025-01-20',
    currentRs: -0.9,
    netPnL: -1000,
  },
  {
    positionId: 'MOCK-QQQ-TSLA-SHORT-3',
    pair: 'QQQ/TSLA',
    baseline: 'QQQ',
    symbol: 'TSLA',
    status: PositionStatus.OPEN,
    direction: PositionDirection.SHORT,
    entryPrice: 250,
    entryDay: '2025-01-09',
    entryTimestamp: Date.UTC(2025, 0, 9),
    currentPrice: 235,
    currentChange: -15,
    currentPctChange: -6,
    lastUpdateDay: '2025-01-20',
    currentRs: 1.3,
    netPnL: 1500,
  },
  {
    positionId: 'MOCK-IWM-SPY-SHORT-4',
    pair: 'IWM/SPY',
    baseline: 'IWM',
    symbol: 'SPY',
    status: PositionStatus.OPEN,
    direction: PositionDirection.SHORT,
    entryPrice: 190,
    entryDay: '2025-01-11',
    entryTimestamp: Date.UTC(2025, 0, 11),
    currentPrice: 188,
    currentChange: -2,
    currentPctChange: -1.05,
    lastUpdateDay: '2025-01-20',
    currentRs: 0.2,
    netPnL: 200,
  },
  {
    positionId: 'MOCK-SPY-IWM-LONG-6',
    pair: 'SPY/IWM',
    baseline: 'SPY',
    symbol: 'IWM',
    status: PositionStatus.OPEN,
    direction: PositionDirection.LONG,
    entryPrice: 75,
    entryDay: '2025-01-02',
    entryTimestamp: Date.UTC(2025, 0, 2),
    currentPrice: 80,
    currentChange: 5,
    currentPctChange: 6.67,
    lastUpdateDay: '2025-01-20',
    currentRs: 0.7,
    netPnL: 500,
  },
];
