/**
 * Validate the V2 historical options contract endpoint against a sample of the
 * matrix generated by build-options-contract-matrix.ts.
 *
 * Usage (from repo root):
 *   npx tsx functions/scripts/validate-options-contract-v2.ts --limit 5
 *   npx tsx functions/scripts/validate-options-contract-v2.ts --years 2025,2026 --limit 1000
 *
 * It uses the existing partner proxy helper so auth/audience logic stays in sync.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { callPartnerHistoricalOptionsContractV2 } from '../src/partner-proxy';
import { PartnerHistoricalOptionsContractV2Response } from '../src/types/partner';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MATRIX_PATH = path.join(__dirname, 'options-contract-matrix.json');

interface ContractCase {
  symbol: string;
  contractID: string;
  expiration: string;
  type: 'call' | 'put';
  strike: number;
  entryDate: string;
  startDate: string;
  endDate: string;
  durationLabel: string;
  underlyingClose: number;
}

function parseArgs(): { limit: number; delayMs: number; years: number[] } {
  const args = process.argv.slice(2);
  const limitIndex = args.indexOf('--limit');
  const delayIndex = args.indexOf('--delay');
  const yearsIndex = args.indexOf('--years');
  const limit = limitIndex >= 0 ? Number(args[limitIndex + 1]) : 5;
  const delayMs = delayIndex >= 0 ? Number(args[delayIndex + 1]) : 500;
  const yearsArg = yearsIndex >= 0 ? args[yearsIndex + 1] : '';
  const years = yearsArg ? yearsArg.split(',').map((s) => Number(s.trim())).filter((n) => Number.isFinite(n)) : [];
  return { limit: Number.isFinite(limit) && limit > 0 ? limit : 5, delayMs: Number.isFinite(delayMs) && delayMs >= 0 ? delayMs : 500, years };
}

function validateResponse(
  resp: PartnerHistoricalOptionsContractV2Response,
  expected: ContractCase,
): { ok: boolean; errors: string[] } {
  const errors: string[] = [];
  if (!resp.ok) errors.push('ok=false');
  if (resp.symbol !== expected.symbol) errors.push(`symbol=${resp.symbol}`);
  if (resp.contractID !== expected.contractID) errors.push(`contractID=${resp.contractID}`);
  if (resp.expiration !== expected.expiration) errors.push(`expiration=${resp.expiration}`);
  if (resp.type !== expected.type) errors.push(`type=${resp.type}`);
  if (!Array.isArray(resp.series)) {
    errors.push('series not an array');
  } else if (resp.series.length === 0) {
    errors.push('series empty');
  } else {
    const first = resp.series[0].date;
    const last = resp.series[resp.series.length - 1].date;
    if (first > last) errors.push('series dates inverted');
    const badObservation = resp.series.find((o) => !o.date || typeof o.date !== 'string');
    if (badObservation) errors.push('observation missing date');
  }
  return { ok: errors.length === 0, errors };
}

async function main() {
  const { limit, delayMs, years } = parseArgs();

  if (!fs.existsSync(MATRIX_PATH)) {
    throw new Error(`Matrix file not found: ${MATRIX_PATH}. Run build-options-contract-matrix.ts first.`);
  }

  const matrix: ContractCase[] = JSON.parse(fs.readFileSync(MATRIX_PATH, 'utf8'));
  const candidates = years.length > 0
    ? matrix.filter((c) => years.includes(Number(c.expiration.split('-')[0])))
    : matrix;
  const sample = candidates.slice(0, limit);

  console.log(`Validating ${sample.length}/${matrix.length} contracts (delay ${delayMs}ms)`);
  let pass = 0;

  for (let i = 0; i < sample.length; i++) {
    const c = sample[i];
    if (i > 0) {
      await new Promise((r) => setTimeout(r, delayMs));
    }

    try {
      const resp = await callPartnerHistoricalOptionsContractV2({
        symbol: c.symbol,
        contractID: c.contractID,
        startDate: c.startDate,
        endDate: c.endDate,
      });
      const check = validateResponse(resp, c);
      if (check.ok) {
        const len = resp.series?.length ?? 0;
        console.log(`PASS ${c.contractID} (${c.durationLabel}, ${c.startDate}..${c.endDate}) → ${len} observations`);
        pass++;
      } else {
        console.log(`FAIL ${c.contractID} (${c.durationLabel}) → ${check.errors.join(', ')}`);
      }
    } catch (err: any) {
      const status = err?.status ?? '??';
      const message = err?.message ?? String(err);
      console.log(`FAIL ${c.contractID} (${c.durationLabel}) → ${message} (status ${status})`);
    }
  }

  console.log(`\nResult: ${pass}/${sample.length} passed`);
  if (pass < sample.length) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Validator crashed:', err);
  process.exit(1);
});
