import { generateTargetRanksData } from './rs-calc-utils';
import { generateTargetRanksDataOptimized } from './rs-calc-utils-optimized';
import { StringNumberObject, BaselineTargetRankDatum } from '../common/interfaces-rs';

/**
 * Compare RS datasets generated by original and optimized methods.
 * Logs mismatches and returns both results for further inspection.
 * @param baseline Array of {date, value} percent changes for baseline
 * @param target Array of {date, value} percent changes for target
 * @param heatmapColors Color map for rank output
 */
export function compareRsDatasets(
  baseline: StringNumberObject[],
  target: StringNumberObject[],
  heatmapColors: string[]
): {
  original: BaselineTargetRankDatum[],
  optimized: BaselineTargetRankDatum[],
  mismatches: Array<{i: number; date: string; orig: number; opt: number}>
} {
  const original = generateTargetRanksData(baseline, target, heatmapColors);
  const optimized = generateTargetRanksDataOptimized(baseline, target, heatmapColors);
  const mismatches = [];
  const len = Math.min(original.length, optimized.length);
  for (let i = 0; i < len; i++) {
    const origVal = Number(original[i].value);
    const optVal = Number(optimized[i].value);
    if (Math.abs(origVal - optVal) > 1e-8) {
      mismatches.push({
        i,
        date: original[i].date,
        orig: origVal,
        opt: optVal
      });
    }
  }
  if (mismatches.length > 0) {
    console.warn('RS calculation mismatches:', mismatches);
  } else {
    console.info('RS calculation: All results match!');
  }
  return { original, optimized, mismatches };
}
