/**
 * RH Agent Cloud Function Config
 *
 * Collection names and constants for the Robinhood Agent Cloud Function.
 */

/** Root collection for agent run records (metadata, status, summary). */
export const RH_AGENT_RUNS_COLLECTION = 'rh-agent-runs';

/** Root collection for individual trade signals generated by the agent. */
export const RH_AGENT_SIGNALS_COLLECTION = 'rh-agent-signals';

/** Singleton doc ID for agent status under rh-agent-status/{AGENT_STATUS_DOC}. */
export const AGENT_STATUS_DOC = 'current';

/** Root collection for agent configuration and status. */
export const RH_AGENT_STATUS_COLLECTION = 'rh-agent-status';

/** Root collection for symbol analysis jobs (subcollection under runs). */
export const RH_AGENT_JOBS_SUBCOLLECTION = 'jobs';

/** Root collection for trade opportunities (user approval workflow). */
export const RH_AGENT_OPPORTUNITIES_COLLECTION = 'rh-agent-opportunities';

/** Symbol list collection for daily scanning. */
export const RH_AGENT_SYMBOLS_COLLECTION = 'rh-agent-symbols';

/**
 * Status of an agent run.
 */
export enum RhAgentRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
}

/**
 * Status of an individual trade signal.
 */
export enum RhSignalStatus {
  GENERATED = 'GENERATED',
  PENDING_EXECUTION = 'PENDING_EXECUTION',
  EXECUTED = 'EXECUTED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  DRY_RUN = 'DRY_RUN',
}

/**
 * Status of a symbol analysis job.
 */
export enum RhAgentJobStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

/**
 * Status of a trade opportunity in approval workflow.
 */
export enum RhOpportunityStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
}

/**
 * Opportunity action type.
 */
export enum RhOpportunityAction {
  BUY = 'BUY',
  SELL = 'SELL',
}

/**
 * Type of trade action.
 */
export enum RhTradeAction {
  BUY = 'BUY',
  SELL = 'SELL',
  HOLD = 'HOLD',
}

/**
 * Agent run record stored in Firestore.
 */
export interface RhAgentRun {
  id: string;
  status: RhAgentRunStatus;
  startedAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  completedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  strategy: string;
  symbol?: string;
  dryRun: boolean;
  triggeredBy?: 'manual' | 'pdr';
  symbolsProcessed: number;
  signalsGenerated: number;
  errors: string[];
  logs: string[];
  summary?: string;
}

/**
 * Trade signal record stored in Firestore.
 */
export interface RhTradeSignal {
  id: string;
  runId: string;
  symbol: string;
  strategy: string;
  action: RhTradeAction;
  status: RhSignalStatus;
  amount?: number;
  quantity?: number;
  price?: number;
  orderType?: 'MARKET' | 'LIMIT' | 'STOP';
  reason: string;
  indicators?: Record<string, number | string>;
  createdAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  executedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  orderId?: string;
  error?: string;
  dryRun: boolean;
}

/**
 * Agent status singleton stored in Firestore.
 */
export interface RhAgentStatus {
  lastRunAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  lastRunId?: string;
  lastRunStatus?: RhAgentRunStatus;
  totalRuns: number;
  totalSignalsGenerated: number;
  isEnabled: boolean;
  schedule?: string;
  symbolsMonitored: string[];
  updatedAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}

/**
 * Configuration for a watched symbol (moved from watchlist.ts for cloud function use).
 */
export interface RhWatchedSymbol {
  symbol: string;
  strategy: 'rsi-oversold' | 'macd-crossover' | 'dip-buy' | 'custom' | 'portfolio-summary' | 'rebalance' | 'watchlist-check' | 'earnings-play';
  amount: number;
  enabled: boolean;
  customPrompt?: string;
  intervalMinutes: number;
}

/**
 * Daily agent run record stored in Firestore.
 * Used for the daily 12:00 PM PT scan of ~700 symbols.
 */
export interface RhAgentDailyRun {
  id: string;
  type: 'daily-scan';
  marketDate: string;  // YYYY-MM-DD
  status: RhAgentRunStatus;
  triggeredBy?: 'manual' | 'pdr';
  totalSymbols: number;
  processedCount: number;
  successCount: number;
  failureCount: number;
  opportunitiesFound: number;
  opportunitiesApproved: number;
  opportunitiesRejected: number;
  opportunitiesExecuted: number;
  startedAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  completedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  deadlineAt: string;  // ISO string - deadline for user approval
  errors?: string[];
  logs?: string[];
}

/**
 * Symbol analysis job stored in Firestore (subcollection under daily run).
 */
export interface RhAgentJob {
  id: string;  // symbol name
  symbol: string;
  status: RhAgentJobStatus;
  attempts: number;
  lastError?: string;
  createdAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  startedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  completedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}

/**
 * Trade opportunity stored in Firestore (user approval workflow).
 */
export interface RhTradeOpportunity {
  id: string;
  runId: string;
  marketDate: string;  // YYYY-MM-DD for easy grouping
  symbol: string;
  action: RhOpportunityAction;
  signalType: string;  // e.g., 'RSI_OVERSOLD', 'MACD_CROSSOVER'
  strategy: 'rsi-oversold' | 'macd-crossover' | 'simple-breakout' | string;
  confidence: number;  // 0-100
  reason: string;
  indicators: Record<string, number>;
  // User-modifiable fields
  suggestedAmount: number;
  amount?: number;  // User override
  orderType: 'MARKET' | 'LIMIT';
  limitPrice?: number;
  // Status workflow
  status: RhOpportunityStatus;
  // Execution details (if executed)
  orderId?: string;
  executedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  executedPrice?: number;
  error?: string;
  // Metadata
  createdAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  updatedAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  approvedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  approvedBy?: string;  // User UID
  rejectedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  rejectedBy?: string;  // User UID
}

/**
 * Symbol list entry for daily scanning.
 */
export interface RhAgentSymbol {
  symbol: string;
  name?: string;
  enabled: boolean;
  priority: number;  // Order of processing (lower = first)
  addedAt: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
  lastAnalyzedAt?: FirebaseFirestore.Timestamp | FirebaseFirestore.FieldValue;
}

/**
 * Cloud Task payload for symbol analysis job.
 */
export interface SymbolJobPayload {
  runId: string;
  symbol: string;
  marketDate: string;  // YYYY-MM-DD
  intraday?: IntradaySnapshot;  // Intraday data from trigger's bulk fetch
}

/**
 * Intraday snapshot data from SavantAPI partnerIntradaySnapshotV2 endpoint.
 */
export interface IntradaySnapshot {
  symbol: string;
  ip: number;      // Latest intraday price
  ipc: number;     // Intraday change %
  io: number;      // Epoch ms timestamp
  it: string;      // Time string (e.g., "10:30")
  ic: number;      // Intraday change $
}
